In [ ]:
#import packages and libraries that will be needed
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
#The package by itself comes with a single module and an estimator.To install the module execute:pip install category_encoders
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegressionCV as LRCV
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
#from functools import partial

In [ ]:
Dataset = pd.read_csv("/content/data.csv")

print(Dataset)

    periodid      periodname  periodcode  perioddescription  \
0     202201    January 2022      202201                NaN
1     202202   February 2022      202202                NaN
2     202203      March 2022      202203                NaN
3     202204      April 2022      202204                NaN
4     202205        May 2022      202205                NaN
5     202206       June 2022      202206                NaN
6     202207       July 2022      202207                NaN
7     202208     August 2022      202208                NaN
8     202209  September 2022      202209                NaN
9     202210    October 2022      202210                NaN
10    202211   November 2022      202211                NaN
11    202212   December 2022      202212                NaN
12    202101    January 2021      202101                NaN
13    202102   February 2021      202102                NaN
14    202103      March 2021      202103                NaN
15    202104      April 2021      202104                NaN
16    202105        May 2021      202105                NaN
17    202106       June 2021      202106                NaN
18    202107       July 2021      202107                NaN
19    202108     August 2021      202108                NaN
20    202109  September 2021      202109                NaN
21    202110    October 2021      202110                NaN
22    202111   November 2021      202111                NaN
23    202112   December 2021      202112                NaN
24    202001    January 2020      202001                NaN
25    202002   February 2020      202002                NaN
26    202003      March 2020      202003                NaN
27    202004      April 2020      202004                NaN
28    202005        May 2020      202005                NaN
29    202006       June 2020      202006                NaN
30    202007       July 2020      202007                NaN
31    202008     August 2020      202008                NaN
32    202009  September 2020      202009                NaN
33    202010    October 2020      202010                NaN
34    202011   November 2020      202011                NaN
35    202012   December 2020      202012                NaN
36    201901    January 2019      201901                NaN
37    201902   February 2019      201902                NaN
38    201903      March 2019      201903                NaN
39    201904      April 2019      201904                NaN
40    201905        May 2019      201905                NaN
41    201906       June 2019      201906                NaN
42    201907       July 2019      201907                NaN
43    201908     August 2019      201908                NaN
44    201909  September 2019      201909                NaN
45    201910    October 2019      201910                NaN
46    201911   November 2019      201911                NaN
47    201912   December 2019      201912                NaN
48    201801    January 2018      201801                NaN
49    201802   February 2018      201802                NaN
50    201803      March 2018      201803                NaN
51    201804      April 2018      201804                NaN
52    201805        May 2018      201805                NaN
53    201806       June 2018      201806                NaN
54    201807       July 2018      201807                NaN
55    201808     August 2018      201808                NaN
56    201809  September 2018      201809                NaN
57    201810    October 2018      201810                NaN
58    201811   November 2018      201811                NaN
59    201812   December 2018      201812                NaN

                     dataid  \
0   cPlWFYbBacW.w77uMi1KzOH
1   cPlWFYbBacW.w77uMi1KzOH
2   cPlWFYbBacW.w77uMi1KzOH
3   cPlWFYbBacW.w77uMi1KzOH
4   cPlWFYbBacW.w77uMi1KzOH
5   cPlWFYbBacW.w77uMi1KzOH
6   cPlWFYbBacW.w77uMi1KzOH
7   cPlWFYbBacW.w77uMi1KzOH
8   cPlWFYbBacW.w77uMi1KzOH
9   cPlWFYbBacW.w77uMi1KzOH
10  cPlWFYbBacW.w77uMi1KzOH
11  cPlWFYbBacW.w77uMi1KzOH
12  cPlWFYbBacW.w77uMi1KzOH
13  cPlWFYbBacW.w77uMi1KzOH
14  cPlWFYbBacW.w77uMi1KzOH
15  cPlWFYbBacW.w77uMi1KzOH
16  cPlWFYbBacW.w77uMi1KzOH
17  cPlWFYbBacW.w77uMi1KzOH
18  cPlWFYbBacW.w77uMi1KzOH
19  cPlWFYbBacW.w77uMi1KzOH
20  cPlWFYbBacW.w77uMi1KzOH
21  cPlWFYbBacW.w77uMi1KzOH
22  cPlWFYbBacW.w77uMi1KzOH
23  cPlWFYbBacW.w77uMi1KzOH
24  cPlWFYbBacW.w77uMi1KzOH
25  cPlWFYbBacW.w77uMi1KzOH
26  cPlWFYbBacW.w77uMi1KzOH
27  cPlWFYbBacW.w77uMi1KzOH
28  cPlWFYbBacW.w77uMi1KzOH
29  cPlWFYbBacW.w77uMi1KzOH
30  cPlWFYbBacW.w77uMi1KzOH
31  cPlWFYbBacW.w77uMi1KzOH
32  cPlWFYbBacW.w77uMi1KzOH
33  cPlWFYbBacW.w77uMi1KzOH
34  cPlWFYbBacW.w77uMi1KzOH
35  cPlWFYbBacW.w77uMi1KzOH
36  cPlWFYbBacW.w77uMi1KzOH
37  cPlWFYbBacW.w77uMi1KzOH
38  cPlWFYbBacW.w77uMi1KzOH
39  cPlWFYbBacW.w77uMi1KzOH
40  cPlWFYbBacW.w77uMi1KzOH
41  cPlWFYbBacW.w77uMi1KzOH
42  cPlWFYbBacW.w77uMi1KzOH
43  cPlWFYbBacW.w77uMi1KzOH
44  cPlWFYbBacW.w77uMi1KzOH
45  cPlWFYbBacW.w77uMi1KzOH
46  cPlWFYbBacW.w77uMi1KzOH
47  cPlWFYbBacW.w77uMi1KzOH
48  cPlWFYbBacW.w77uMi1KzOH
49  cPlWFYbBacW.w77uMi1KzOH
50  cPlWFYbBacW.w77uMi1KzOH
51  cPlWFYbBacW.w77uMi1KzOH
52  cPlWFYbBacW.w77uMi1KzOH
53  cPlWFYbBacW.w77uMi1KzOH
54  cPlWFYbBacW.w77uMi1KzOH
55  cPlWFYbBacW.w77uMi1KzOH
56  cPlWFYbBacW.w77uMi1KzOH
57  cPlWFYbBacW.w77uMi1KzOH
58  cPlWFYbBacW.w77uMi1KzOH
59  cPlWFYbBacW.w77uMi1KzOH

                                             dataname  datacode  \
0   MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
1   MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
2   MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
3   MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
4   MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
5   MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
6   MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
7   MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
8   MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
9   MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
10  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
11  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
12  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
13  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
14  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
15  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
16  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
17  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
18  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
19  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
20  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
21  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
22  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
23  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
24  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
25  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
26  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
27  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
28  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
29  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
30  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
31  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
32  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
33  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
34  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
35  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
36  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
37  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
38  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
39  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
40  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
41  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
42  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
43  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
44  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
45  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
46  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
47  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
48  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
49  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
50  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
51  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
52  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
53  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
54  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
55  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
56  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
57  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
58  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN
59  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...       NaN

    datadescription  Baringo County  Bomet County  ...  Siaya County  \
0               NaN          2644.0         626.0  ...       67556.0
1               NaN          3529.0         444.0  ...       52890.0
2               NaN          2998.0         460.0  ...       50940.0
3               NaN          2755.0         508.0  ...       41512.0
4               NaN          2878.0         355.0  ...       63304.0
5               NaN          3433.0         938.0  ...       83359.0
6               NaN          2286.0         154.0  ...       74986.0
7               NaN          2908.0         198.0  ...       57022.0
8               NaN          5001.0         183.0  ...       49401.0
9               NaN          3934.0         135.0  ...       57960.0
10              NaN          2774.0         104.0  ...       59271.0
11              NaN          3300.0          91.0  ...       47610.0
12              NaN          3176.0         548.0  ...       23913.0
13              NaN         10559.0        1222.0  ...       36822.0
14              NaN          4618.0        2002.0  ...       48952.0
15              NaN          3911.0        1634.0  ...       44158.0
16              NaN          3923.0        1050.0  ...       68957.0
17              NaN          3858.0        1265.0  ...       54471.0
18              NaN          3722.0        1237.0  ...       23273.0
19              NaN          4933.0         903.0  ...       48330.0
20              NaN          4806.0         871.0  ...       54066.0
21              NaN          3054.0        1601.0  ...       48661.0
22              NaN          2725.0        1008.0  ...       50844.0
23              NaN          3080.0        1071.0  ...       65691.0
24              NaN          4521.0        1073.0  ...       43450.0
25              NaN          8826.0        1233.0  ...       72773.0
26              NaN          8935.0        1021.0  ...       73676.0
27              NaN          4403.0        1199.0  ...       45956.0
28              NaN          2354.0        1205.0  ...       42170.0
29              NaN          2792.0        1339.0  ...       31851.0
30              NaN          2347.0        1179.0  ...       18305.0
31              NaN          2544.0         831.0  ...       21834.0
32              NaN          4593.0         531.0  ...       41600.0
33              NaN          1826.0         476.0  ...       48086.0
34              NaN          2128.0         576.0  ...       49169.0
35              NaN          3040.0         162.0  ...       19771.0
36              NaN          1670.0        1035.0  ...       73559.0
37              NaN           955.0        1024.0  ...       53192.0
38              NaN          2187.0        1946.0  ...       63059.0
39              NaN          2038.0        1491.0  ...       62994.0
40              NaN          2406.0        1856.0  ...       82758.0
41              NaN          1922.0        1613.0  ...       86615.0
42              NaN          2315.0        1755.0  ...      113219.0
43              NaN          1687.0        1352.0  ...       62625.0
44              NaN          2866.0        1415.0  ...       32587.0
45              NaN          1581.0        1094.0  ...       11445.0
46              NaN          2403.0         980.0  ...        6621.0
47              NaN          2398.0         756.0  ...        5498.0
48              NaN          1711.0        1259.0  ...       60626.0
49              NaN          2617.0        2370.0  ...       59617.0
50              NaN          2101.0        2144.0  ...       45145.0
51              NaN          1269.0        2033.0  ...       56371.0
52              NaN          2955.0        1722.0  ...       96324.0
53              NaN          4017.0        2143.0  ...       96213.0
54              NaN          4122.0        2294.0  ...       38665.0
55              NaN          2226.0        1423.0  ...       12623.0
56              NaN          1007.0        1894.0  ...        8157.0
57              NaN          1155.0        1248.0  ...        4530.0
58              NaN           793.0         730.0  ...       28846.0
59              NaN          1113.0        1032.0  ...       46337.0

    Taita Taveta County  Tana River County  Tharaka Nithi County  \
0                 496.0             4000.0                1148.0
1                 983.0             2889.0                1398.0
2                1015.0             2392.0                 671.0
3                 698.0             1567.0                 509.0
4                 748.0             2239.0                1507.0
5                1044.0             1980.0                 920.0
6                1096.0             1672.0                 495.0
7                 724.0             4769.0                 499.0
8                 441.0             1094.0                 353.0
9                 332.0             1078.0                 360.0
10                388.0             1450.5                 510.0
11                680.0             1268.0                 500.0
12                 46.0              559.0                 300.0
13                164.0              332.0                 307.0
14                422.0              134.0                 317.0
15                308.0              464.0                 384.0
16                267.0              795.0                 288.0
17                211.0              943.0                 375.0
18                603.0             2035.0                 490.0
19               1322.0             2772.0                 309.0
20               1045.0             2198.0                1403.0
21                796.0             2685.0                 979.0
22                724.0             2926.0                1943.0
23                737.0             2672.0                1094.0
24               1114.0             2540.0                1132.0
25                791.0             2169.0                1080.0
26                719.0             1750.0                1333.0
27                486.0              865.0                 639.0
28                493.0              598.0                 903.0
29                443.0              890.0                1122.0
30                300.0              856.0                1047.0
31                316.0              909.0                 769.0
32                298.0              458.0                 556.0
33                392.0             1000.0                 566.0
34                622.0             1103.0                 417.0
35                 96.0              380.0                 232.0
36                436.0             1771.0                1023.0
37                488.0              570.0                1182.0
38                888.0              246.0                1582.0
39                943.0              169.0                 474.0
40               1052.0              213.0                1581.0
41               1393.0              612.0                2206.0
42               2484.0             1119.0                1456.0
43               1507.0             1300.0                1787.0
44                840.0              679.0                 805.0
45                937.0             1163.0                 878.0
46                701.0             1316.0                 651.0
47               1522.0             1197.0                 548.0
48                863.0             5648.0                 242.0
49                857.0             2952.0                1490.0
50               1506.0             1883.0                1301.0
51               1482.0             2410.0                 985.0
52               1710.0             2722.0                1237.0
53               1152.0             2848.0                 204.0
54                849.0             2314.0                  85.0
55                496.0              678.0                   6.0
56                586.0              196.0                   6.0
57                182.0              223.0                  25.0
58                 68.0              344.0                 852.0
59                 90.0              716.0                 771.0

    Trans Nzoia County  Turkana County  Uasin Gishu County  Vihiga County  \
0               4598.0         31277.0              3127.0        29950.0
1               5390.0         23382.0              2006.0        20458.0
2               6367.0         19729.0              2093.0        19161.0
3               5187.0         22980.0              1221.0        18753.0
4              11820.0         35963.0              1595.0        34762.0
5              18132.0         49040.0              1818.0        51338.0
6               8895.0         51750.0               574.0        32683.0
7               6856.0         61039.0              1768.0        26097.0
8               4751.0         75068.0              1745.0        20625.0
9               3562.0         59403.0              1360.0        22618.0
10              6388.0         30803.0              2015.0        20274.0
11              7082.0         29178.0              1320.0        14093.0
12               833.0         28774.0              2207.0         3408.0
13              1027.0         27973.0              2885.0         7195.0
14              7330.0         21320.0              2578.0        29295.0
15              6350.0         17649.0              1615.0        23247.0
16              8526.0         25392.0              3515.0        34579.0
17              9240.0         34468.0              3137.0        45188.0
18              6673.0         56410.0              1371.0        30821.0
19              7201.0         77915.0              5269.0        39287.0
20             10618.0         58358.0              2696.0        44289.0
21              7128.0         46473.0              2515.0        22321.0
22              7334.0         36503.0              2948.0        30136.0
23              6747.0         28407.0              3978.0        30341.0
24                96.0         37484.0              2706.0          825.0
25              2806.0         41015.0              4252.0         7075.0
26              6562.0         20919.0              3989.0        24464.0
27              3670.0         15863.0              2343.0        13198.0
28              4018.0         26454.0              1577.0        20588.0
29              2771.0         16941.0              2175.0        22679.0
30              2676.0         29457.0              2494.0        16268.0
31              3753.0         50516.0              2105.0         9583.0
32              5058.0         54876.0              1292.0        15393.0

In [ ]:
Dataset.isnull().sum()

periodid                   0
periodname                 0
periodcode                 0
perioddescription         60
dataid                     0
dataname                   0
datacode                  60
datadescription           60
Baringo County             0
Bomet County               0
Bungoma County             0
Busia County               0
Elgeyo Marakwet County     0
Embu County                1
Garissa County             0
Homa Bay County            0
Isiolo County              0
Kajiado County             0
Kakamega County            0
Kericho County             0
Kiambu County              0
Kilifi County              0
Kirinyaga County           3
Kisii County               0
Kisumu County              0
Kitui County               0
Kwale County               0
Laikipia County            0
Lamu County                0
Machakos County            0
Makueni County             0
Mandera County             7
Marsabit County            0
Meru County                0
Migori County              0
Mombasa County             0
Muranga County            12
Nairobi County             0
Nakuru County              0
Nandi County               0
Narok County               0
Nyamira County             3
Nyandarua County           0
Nyeri County               0
Samburu County             0
Siaya County               0
Taita Taveta County        0
Tana River County          0
Tharaka Nithi County       0
Trans Nzoia County         0
Turkana County             0
Uasin Gishu County         0
Vihiga County              0
Wajir County               0
West Pokot County          0
dtype: int64

In [ ]:
print(Dataset.shape)

(60, 55)

In [ ]:
# Replace missing values (-) with 0 in the columns 'Meru County', 'Kirinyaga County', 'Muranga County', 'Mandera County', and 'Nyamira County'
for col in ['Meru County', 'Kirinyaga County', 'Muranga County', 'Mandera County', 'Nyamira County']:
    Dataset[col] = Dataset[col].astype(str).str.replace('-', '0')

In [ ]:
from re import X
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

# Extract numerical features from date
Dataset['year'] = pd.to_datetime(Dataset['periodname']).dt.year
Dataset['month'] = pd.to_datetime(Dataset['periodname']).dt.month

# Select the columns to scale
X = Dataset[['year', 'month']]

# Scale the data
scaler = StandardScaler()
X_normalized = scaler.fit_transform(X)

#show the values
print(X_normalized)#not sure what X_normalized values represent

[[ 1.41421356 -1.59325501]
 [ 1.41421356 -1.30357228]
 [ 1.41421356 -1.01388955]
 [ 1.41421356 -0.72420682]
 [ 1.41421356 -0.43452409]
 [ 1.41421356 -0.14484136]
 [ 1.41421356  0.14484136]
 [ 1.41421356  0.43452409]
 [ 1.41421356  0.72420682]
 [ 1.41421356  1.01388955]
 [ 1.41421356  1.30357228]
 [ 1.41421356  1.59325501]
 [ 0.70710678 -1.59325501]
 [ 0.70710678 -1.30357228]
 [ 0.70710678 -1.01388955]
 [ 0.70710678 -0.72420682]
 [ 0.70710678 -0.43452409]
 [ 0.70710678 -0.14484136]
 [ 0.70710678  0.14484136]
 [ 0.70710678  0.43452409]
 [ 0.70710678  0.72420682]
 [ 0.70710678  1.01388955]
 [ 0.70710678  1.30357228]
 [ 0.70710678  1.59325501]
 [ 0.         -1.59325501]
 [ 0.         -1.30357228]
 [ 0.         -1.01388955]
 [ 0.         -0.72420682]
 [ 0.         -0.43452409]
 [ 0.         -0.14484136]
 [ 0.          0.14484136]
 [ 0.          0.43452409]
 [ 0.          0.72420682]
 [ 0.          1.01388955]
 [ 0.          1.30357228]
 [ 0.          1.59325501]
 [-0.70710678 -1.59325501]
 [-0.70710678 -1.30357228]
 [-0.70710678 -1.01388955]
 [-0.70710678 -0.72420682]
 [-0.70710678 -0.43452409]
 [-0.70710678 -0.14484136]
 [-0.70710678  0.14484136]
 [-0.70710678  0.43452409]
 [-0.70710678  0.72420682]
 [-0.70710678  1.01388955]
 [-0.70710678  1.30357228]
 [-0.70710678  1.59325501]
 [-1.41421356 -1.59325501]
 [-1.41421356 -1.30357228]
 [-1.41421356 -1.01388955]
 [-1.41421356 -0.72420682]
 [-1.41421356 -0.43452409]
 [-1.41421356 -0.14484136]
 [-1.41421356  0.14484136]
 [-1.41421356  0.43452409]
 [-1.41421356  0.72420682]
 [-1.41421356  1.01388955]
 [-1.41421356  1.30357228]
 [-1.41421356  1.59325501]]

In [ ]:
print(Dataset.dtypes)

periodid                    int64
periodname                 object
periodcode                  int64
perioddescription         float64
dataid                     object
dataname                   object
datacode                  float64
datadescription           float64
Baringo County            float64
Bomet County              float64
Bungoma County            float64
Busia County              float64
Elgeyo Marakwet County    float64
Embu County               float64
Garissa County            float64
Homa Bay County           float64
Isiolo County             float64
Kajiado County            float64
Kakamega County           float64
Kericho County            float64
Kiambu County             float64
Kilifi County             float64
Kirinyaga County           object
Kisii County              float64
Kisumu County             float64
Kitui County              float64
Kwale County              float64
Laikipia County           float64
Lamu County               float64
Machakos County           float64
Makueni County            float64
Mandera County             object
Marsabit County           float64
Meru County                object
Migori County             float64
Mombasa County            float64
Muranga County             object
Nairobi County            float64
Nakuru County             float64
Nandi County              float64
Narok County              float64
Nyamira County             object
Nyandarua County          float64
Nyeri County              float64
Samburu County            float64
Siaya County              float64
Taita Taveta County       float64
Tana River County         float64
Tharaka Nithi County      float64
Trans Nzoia County        float64
Turkana County            float64
Uasin Gishu County        float64
Vihiga County             float64
Wajir County              float64
West Pokot County         float64
year                        int64
month                       int64
dtype: object

In [ ]:
# change data type of 'Meru County', 'Kirinyaga County', 'Muranga County', 'Mandera County', 'Nyamira County' columns to float
Dataset[['Meru County', 'Kirinyaga County', 'Muranga County', 'Mandera County', 'Nyamira County']] = Dataset[['Meru County', 'Kirinyaga County', 'Muranga County', 'Mandera County', 'Nyamira County']].astype(float)

In [ ]:
print(Dataset.dtypes)

periodid                    int64
periodname                 object
periodcode                  int64
perioddescription         float64
dataid                     object
dataname                   object
datacode                  float64
datadescription           float64
Baringo County            float64
Bomet County              float64
Bungoma County            float64
Busia County              float64
Elgeyo Marakwet County    float64
Embu County               float64
Garissa County            float64
Homa Bay County           float64
Isiolo County             float64
Kajiado County            float64
Kakamega County           float64
Kericho County            float64
Kiambu County             float64
Kilifi County             float64
Kirinyaga County          float64
Kisii County              float64
Kisumu County             float64
Kitui County              float64
Kwale County              float64
Laikipia County           float64
Lamu County               float64
Machakos County           float64
Makueni County            float64
Mandera County            float64
Marsabit County           float64
Meru County               float64
Migori County             float64
Mombasa County            float64
Muranga County            float64
Nairobi County            float64
Nakuru County             float64
Nandi County              float64
Narok County              float64
Nyamira County            float64
Nyandarua County          float64
Nyeri County              float64
Samburu County            float64
Siaya County              float64
Taita Taveta County       float64
Tana River County         float64
Tharaka Nithi County      float64
Trans Nzoia County        float64
Turkana County            float64
Uasin Gishu County        float64
Vihiga County             float64
Wajir County              float64
West Pokot County         float64
year                        int64
month                       int64
dtype: object

In [ ]:
# replace missing values with 0
Dataset[['Meru County', 'Kirinyaga County', 'Muranga County', 'Mandera County', 'Nyamira County']] = Dataset[['Meru County', 'Kirinyaga County', 'Muranga County', 'Mandera County', 'Nyamira County']].fillna(0)

In [ ]:
# Read in the CSV file
import pandas as pd
Dataset = pd.read_csv("/content/data.csv")

# Replace 0s with column mean
Dataset = Dataset.replace(0, Dataset.mean())

<ipython-input-157-2efe2fd371af>:6: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  Dataset = Dataset.replace(0, Dataset.mean())

In [ ]:
Dataset.head(10)

,periodid,periodname,periodcode,perioddescription,dataid,dataname,datacode,datadescription,Baringo County,Bomet County,...,Siaya County,Taita Taveta County,Tana River County,Tharaka Nithi County,Trans Nzoia County,Turkana County,Uasin Gishu County,Vihiga County,Wajir County,West Pokot County
0,202201,January 2022,202201,NaN,cPlWFYbBacW.w77uMi1KzOH,MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...,NaN,NaN,2644.0,626.0,...,67556.0,496.0,4000.0,1148.0,4598.0,31277.0,3127.0,29950.0,1146.0,8189.0
1,202202,February 2022,202202,NaN,cPlWFYbBacW.w77uMi1KzOH,MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...,NaN,NaN,3529.0,444.0,...,52890.0,983.0,2889.0,1398.0,5390.0,23382.0,2006.0,20458.0,1197.0,6908.0
2,202203,March 2022,202203,NaN,cPlWFYbBacW.w77uMi1KzOH,MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...,NaN,NaN,2998.0,460.0,...,50940.0,1015.0,2392.0,671.0,6367.0,19729.0,2093.0,19161.0,885.0,6343.0
3,202204,April 2022,202204,NaN,cPlWFYbBacW.w77uMi1KzOH,MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...,NaN,NaN,2755.0,508.0,...,41512.0,698.0,1567.0,509.0,5187.0,22980.0,1221.0,18753.0,936.0,9657.0
4,202205,May 2022,202205,NaN,cPlWFYbBacW.w77uMi1KzOH,MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...,NaN,NaN,2878.0,355.0,...,63304.0,748.0,2239.0,1507.0,11820.0,35963.0,1595.0,34762.0,1236.0,13388.0
5,202206,June 2022,202206,NaN,cPlWFYbBacW.w77uMi1KzOH,MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...,NaN,NaN,3433.0,938.0,...,83359.0,1044.0,1980.0,920.0,18132.0,49040.0,1818.0,51338.0,394.0,14466.0
6,202207,July 2022,202207,NaN,cPlWFYbBacW.w77uMi1KzOH,MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...,NaN,NaN,2286.0,154.0,...,74986.0,1096.0,1672.0,495.0,8895.0,51750.0,574.0,32683.0,208.0,12226.0
7,202208,August 2022,202208,NaN,cPlWFYbBacW.w77uMi1KzOH,MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...,NaN,NaN,2908.0,198.0,...,57022.0,724.0,4769.0,499.0,6856.0,61039.0,1768.0,26097.0,516.0,11452.0
8,202209,September 2022,202209,NaN,cPlWFYbBacW.w77uMi1KzOH,MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...,NaN,NaN,5001.0,183.0,...,49401.0,441.0,1094.0,353.0,4751.0,75068.0,1745.0,20625.0,812.0,17359.0
9,202210,October 2022,202210,NaN,cPlWFYbBacW.w77uMi1KzOH,MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...,NaN,NaN,3934.0,135.0,...,57960.0,332.0,1078.0,360.0,3562.0,59403.0,1360.0,22618.0,976.0,15665.0

In [ ]:
# Assume your dataframe is named 'df'
Dataset.drop(['periodid', 'periodcode', 'perioddescription', 'dataid','dataname', 'datacode', 'datadescription'], axis=1, inplace=True)

In [ ]:
print(Dataset.shape)

(60, 48)

In [ ]:
Dataset.head(10)

,periodname,Baringo County,Bomet County,Bungoma County,Busia County,Elgeyo Marakwet County,Embu County,Garissa County,Homa Bay County,Isiolo County,...,Siaya County,Taita Taveta County,Tana River County,Tharaka Nithi County,Trans Nzoia County,Turkana County,Uasin Gishu County,Vihiga County,Wajir County,West Pokot County
0,January 2022,2644.0,626.0,24500.0,46485.0,2055.0,874.0,1003.0,50250.0,116.0,...,67556.0,496.0,4000.0,1148.0,4598.0,31277.0,3127.0,29950.0,1146.0,8189.0
1,February 2022,3529.0,444.0,19890.0,32549.0,1771.0,608.0,1453.0,30761.0,153.0,...,52890.0,983.0,2889.0,1398.0,5390.0,23382.0,2006.0,20458.0,1197.0,6908.0
2,March 2022,2998.0,460.0,21699.0,35408.0,1513.0,548.0,1100.0,36386.0,122.0,...,50940.0,1015.0,2392.0,671.0,6367.0,19729.0,2093.0,19161.0,885.0,6343.0
3,April 2022,2755.0,508.0,21538.0,31264.0,803.0,489.0,823.0,35796.0,130.0,...,41512.0,698.0,1567.0,509.0,5187.0,22980.0,1221.0,18753.0,936.0,9657.0
4,May 2022,2878.0,355.0,29388.0,48631.0,335.0,469.0,2227.0,32456.0,210.0,...,63304.0,748.0,2239.0,1507.0,11820.0,35963.0,1595.0,34762.0,1236.0,13388.0
5,June 2022,3433.0,938.0,48301.0,66881.0,126.0,310.0,480.0,56290.0,482.0,...,83359.0,1044.0,1980.0,920.0,18132.0,49040.0,1818.0,51338.0,394.0,14466.0
6,July 2022,2286.0,154.0,30519.0,58220.0,140.0,385.0,272.0,57169.0,222.0,...,74986.0,1096.0,1672.0,495.0,8895.0,51750.0,574.0,32683.0,208.0,12226.0
7,August 2022,2908.0,198.0,22585.0,39618.0,1049.0,378.0,241.0,39336.0,513.0,...,57022.0,724.0,4769.0,499.0,6856.0,61039.0,1768.0,26097.0,516.0,11452.0
8,September 2022,5001.0,183.0,20930.0,31728.0,1763.0,265.0,515.0,37450.0,238.0,...,49401.0,441.0,1094.0,353.0,4751.0,75068.0,1745.0,20625.0,812.0,17359.0
9,October 2022,3934.0,135.0,20739.0,29787.0,2243.0,73.0,354.0,53717.0,1284.0,...,57960.0,332.0,1078.0,360.0,3562.0,59403.0,1360.0,22618.0,976.0,15665.0

In [ ]:
import pandas as pd

# Read the CSV file into a Pandas DataFrame
Dataset = pd.read_csv("/content/data.csv")
# Create a new column 'date' with the date value extracted from the 'periodname' column
Dataset['date'] = pd.to_datetime(Dataset['periodname'], format='%B %Y')

# Check the result
print(Dataset.head())

   periodid     periodname  periodcode  perioddescription  \
0    202201   January 2022      202201                NaN
1    202202  February 2022      202202                NaN
2    202203     March 2022      202203                NaN
3    202204     April 2022      202204                NaN
4    202205       May 2022      202205                NaN

                    dataid                                           dataname  \
0  cPlWFYbBacW.w77uMi1KzOH  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...
1  cPlWFYbBacW.w77uMi1KzOH  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...
2  cPlWFYbBacW.w77uMi1KzOH  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...
3  cPlWFYbBacW.w77uMi1KzOH  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...
4  cPlWFYbBacW.w77uMi1KzOH  MOH 743 Rev2020_Rapid Diagnostic Tests Total Q...

   datacode  datadescription  Baringo County  Bomet County  ...  \
0       NaN              NaN          2644.0         626.0  ...
1       NaN              NaN          3529.0         444.0  ...
2       NaN              NaN          2998.0         460.0  ...
3       NaN              NaN          2755.0         508.0  ...
4       NaN              NaN          2878.0         355.0  ...

   Taita Taveta County  Tana River County  Tharaka Nithi County  \
0                496.0             4000.0                1148.0
1                983.0             2889.0                1398.0
2               1015.0             2392.0                 671.0
3                698.0             1567.0                 509.0
4                748.0             2239.0                1507.0

   Trans Nzoia County  Turkana County  Uasin Gishu County  Vihiga County  \
0              4598.0         31277.0              3127.0        29950.0
1              5390.0         23382.0              2006.0        20458.0
2              6367.0         19729.0              2093.0        19161.0
3              5187.0         22980.0              1221.0        18753.0
4             11820.0         35963.0              1595.0        34762.0

   Wajir County  West Pokot County       date
0        1146.0             8189.0 2022-01-01
1        1197.0             6908.0 2022-02-01
2         885.0             6343.0 2022-03-01
3         936.0             9657.0 2022-04-01
4        1236.0            13388.0 2022-05-01

[5 rows x 56 columns]

In [ ]:
Dataset.drop(['periodname'], axis=1, inplace=True)

In [ ]:
#Dependant variable selection
Dependant = Dataset.loc[:,['Kiambu County', 'Siaya County', 'Narok County', 'Turkana County', 'Meru County']]

#Independent variable selection
Independent = Dataset.loc[:,['date']]
print(Dependant.head(5))
print(Independent.head(5))

   Kiambu County  Siaya County  Narok County  Turkana County  Meru County
0          306.0       67556.0         143.0         31277.0       2773.0
1          353.0       52890.0         434.0         23382.0       2700.0
2          755.0       50940.0         699.0         19729.0       1912.0
3          369.0       41512.0        1432.0         22980.0        935.0
4          658.0       63304.0        1949.0         35963.0       1827.0
        date
0 2022-01-01
1 2022-02-01
2 2022-03-01
3 2022-04-01
4 2022-05-01

In [ ]:
print(Dataset.dtypes)

periodname                 object
Baringo County            float64
Bomet County              float64
Bungoma County            float64
Busia County              float64
Elgeyo Marakwet County    float64
Embu County               float64
Garissa County            float64
Homa Bay County           float64
Isiolo County             float64
Kajiado County            float64
Kakamega County           float64
Kericho County            float64
Kiambu County             float64
Kilifi County             float64
Kirinyaga County          float64
Kisii County              float64
Kisumu County             float64
Kitui County              float64
Kwale County              float64
Laikipia County           float64
Lamu County               float64
Machakos County           float64
Makueni County            float64
Mandera County            float64
Marsabit County           float64
Meru County               float64
Migori County             float64
Mombasa County            float64
Muranga County            float64
Nairobi County            float64
Nakuru County             float64
Nandi County              float64
Narok County              float64
Nyamira County            float64
Nyandarua County          float64
Nyeri County              float64
Samburu County            float64
Siaya County              float64
Taita Taveta County       float64
Tana River County         float64
Tharaka Nithi County      float64
Trans Nzoia County        float64
Turkana County            float64
Uasin Gishu County        float64
Vihiga County             float64
Wajir County              float64
West Pokot County         float64
dtype: object

In [ ]:
from sklearn.model_selection import train_test_split

X = Dataset.drop(['Kiambu County', 'Siaya County', 'Narok County', 'Turkana County', 'Meru County'], axis=1) # independent variables
y = Dataset[['date']] # dependent variables

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Load your dataset
Dataset = pd.read_csv("/content/data.csv")

# Convert the periodname column to one-hot encoded variables
Dataset = pd.get_dummies(Dataset, columns=["periodname"])

KeyError: ignored

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

# Split data into training and testing sets
# X_train and X_test should contain the independent variables for all counties
# y_train and y_test should contain the demand for all counties
# Make sure that the samples in X_train and X_test match the corresponding samples in y_train and y_test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Make predictions on the standardized testing set
X_test = scaler.transform(X_test)


# Inverse transform the predicted values to get the actual demand predictions
y_pred = scaler.inverse_transform(y_pred)

# Evaluate the performance of the model using mean squared error

ValueError: ignored

In [ ]:
y_pred = y_pred.reshape(-1, 1)

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error

# Split data into training and testing sets
# X_train and X_test should contain the independent variables for all counties
# y_train and y_test should contain the demand for all counties
# Make sure that the samples in X_train and X_test match the corresponding samples in y_train and y_test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

# Fit the regression model to the standardized training set
regressor = LinearRegression()
regressor.fit(X_train, y_train)

# Make predictions on the standardized testing set
X_test = scaler.transform(X_test)
y_pred = regressor.predict(X_test)

# Inverse transform the predicted values to get the actual demand predictions
y_pred = scaler.inverse_transform(y_pred)

# Evaluate the performance of the model using mean squared error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

ValueError: ignored

In [ ]:

# Inverse transform the predicted values to get the actual demand predictions
y_pred = scaler.inverse_transform(y_pred.reshape(1, -1)).reshape(-1, 2)

ValueError: ignored

In [ ]:
y_pred = scaler.inverse_transform(y_pred.reshape(-1, 2)).reshape(-1, )

In [ ]:
y_test = y_test.astype('float64')

TypeError: ignored

In [ ]:
import numpy as np

# convert numpy array to float64
y_test = y_test.astype('float64')

In [ ]:
from sklearn.metrics import mean_squared_error

# Calculate the MSE of the model
mse = mean_squared_error(y_test, y_pred)

# Print the MSE
print('MSE:', mse)

MSE: 2.738860293486622e+40

In [ ]:
from sklearn.metrics import mean_squared_error

# Calculate the MSE of the model
mse = mean_squared_error(y_test, y_pred)

# Print the MSE
print("Mean Squared Error: ", mse)